aws_region            = "eu-central-1"
vpc_cidr              = "10.0.0.0/16"
public_subnet_cidr    = "10.0.1.0/24"
availability_zone     = "eu-central-1a"
my_ip                 = "79.177.155.192/32"
role_name             = "Moveo-EC2Role"
instance_type         = "t3.large"
instance_profile_name = "Moveo-EC2Role"